init: create /dev/root if not done in stage 1
When running nixops-libvirt with a host kernel via the command line

      cmdline="root=/dev/sda1 earlycon=ttyS0 console=ttyS0
      init=/nix/var/nix/profiles/system/init boot.debug=1 boot.consoleLogLevel=1 ";
      kernel="/host/kernel/arch/x86_64/boot/bzImage";

/proc/cmdline can't be read in stage 1 and thus /dev/root doesn't exist
which makes `nixops deploy` fail with

==========
client> copying closure...
server> copying closure...
e> closures copied successfully
client> updating GRUB 2 menu...
client> Failed to get blkid info for / on /dev/root at /nix/store/s54azprbp2ic2zpb7df2kb2pafmcrsdi-install-grub.pl line 185.
client> error: Traceback (most recent call last):
  File "/home/teto/nixops/nixops/deployment.py", line 705, in worker
    raise Exception("unable to activate new configuration")
Exception: unable to activate new configuration
==========

Solves
https://github.com/NixOS/nixpkgs/issues/32406
https://github.com/NixOS/nixops/issues/795